language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: uQpoW21kZLoIziEwKXHhT+DfLaEo+ID2YBJ6tpjLlskibLn/kwtW4HfIycMq9xAB/nEvosYcq50JNraFjSywTb+/eyrTbhxWV3KAYFlGo59cqwSntACxe6VKJzsiDk9CgIiDWMTIGClOgkp+CjQF9HksZCRHlQ0vHhPYQwgyrQPYSmlfUN0wZc4z+lHYTm+f5D30JP3TXox2oWiq82EBqHbHU88sMkd/217MPIgU2AUJrlNcQpQ1jARnE5cjHfelehcP9hJxiiNy2Ai5Cul6bDzU8lxHQF5LhaqSaLfF3bHQZtE8lZBrSZYzZtyXBcZqtfjOz+TMdZKuqhLk3VAWNdvqlx7STNhSxwHV5ABYTpZ0PsYQY5jviO+wBjj5m3Og67RBWPvIcxSoQsPnjH5as0wKNby7mIbCCeKCEK/WGJtoe03B54SkKIm6EF/KvrE7tqizxBjPc9j7xkkSBRn/jZNVaUUhghgRSHDuhlwc5ZFYvO/wL9lztnKFuPwwPLDELsIrIHP0rcorPTtSb3K3NitTmKNyesvn51FX1Td+ox2XmyEWCARCQkJWm/tS4mhDw8AL/MympTBDWpwlpJqiRXAb2d4mQGGlWXzirILrgcWWp9RtTaKy27Ix9HCNITLHrEXWXdQTwSvCeLAhy2HqaeR0na6an2MOHU2/mJMq+6Y=
  app: fstopandgo
  on:
    repo: AlexWarnes/fStopandGo
