language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: PAB4BJNSRBrVS9oQ0vv+Y/grcrKkpGk2XrGIP3vtI8zaXeWOF5hOEIJECc9x5a7lquEef6JQg3wNrgPksVoiasq5kXdMCLQ/QH7mpBJeWCZquD+Uy4wn9wNYxpsTqb9AbLVSyIp8zh03oml4RF3hjwc6Z7wwLbTokLo5A3LdWtZbU28IIem+WyL//hTDjE3Qe4wIq9xORK+0ysUM7OltCqb+5dX6ikQfWWPhRPylh4kN+f7Ep3Utx1/Pv494OHCHG/ub16xoLYwVbHoZagGlI+nX+lk+BzX4snaA05HyGZRRJG8SWQroqbaRBlm28GZzc/YnOiXBBLxjU7Dg/9yHYUdNlD00aqsYV6V/RZyq77b6mycj2bb+i8eAbBqz/T9ewf9wPuDM1el8RuyE23J/1lytQsu09/vI0CzGNQMlR8ymoYs/UNBdYZrURjuoeUM6Axe2SB1O9y31l7e0decp3XPTfbCUoUgozgUANFOYMPG8eg1MBaMnSKxIYrZhUwMIGx4bwhiebiWweyhSz66Z5qtb6e/LDRzkYPxrxEG8ByyuOA1H6o0rXH5ByONtA+D8FA0K06RaO8wsj9COYuBSIGB2eFabl+/1ooHHC8a0/uTdfybISNtv0kLbZqHAbqjDD8Rj+WaRbDErMvjOZJx5j2iUN7V1I3DwCy7fLnVC128=
  app: fstopandgo
  on:
    repo: AlexWarnes/fStopandGo

